version: '3.8'
services:
  web:
    container_name: go-test
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zuruck
      POSTGRES_DB: test_db
    volumes: 
      - db-data:/var/lib/postgressql/data
volumes:
  db-data:
