version: '3.8'
services:
  web:
    container_name: go-test-debug
    build: 
      context: .
      dockerfile: ./debug.dockerfile
    ports:
      - "8080:8080"
      - "4000:4000"
    environment:
      - PORT=8080
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes: 
      - db-data:/var/lib/postgressql/data
volumes:
  db-data:
