version: '3.8'
services:
  web:
    container_name: go-test-web-debug
    build: 
      context: .
      dockerfile: ./docker/web.debug.dockerfile
    ports:
      - "8080:8080"
      - "4000:4000"
    environment:
      - PORT=8080
    depends_on:
      - db
    networks:
      - internal
  db:
    container_name: go-test-db
    build:
      context: .
      dockerfile: ./docker/db.dockerfile
    restart: always
    env_file:
      - .env
    volumes: 
      - db-data:/var/lib/postgressql/data
      - ./docker/dataset:/docker-entrypoint-initdb.d
    networks:
      - internal
volumes:
  db-data:
networks:
  internal:
    driver: bridge